
import type { Medicine, Doctor, Hospital } from './definitions';

export const medicines: Medicine[] = [
  {
    id: 'med-001',
    name: 'Exaspirin',
    genericName: 'Aspirinum exempli',
    description:
      'Exaspirin is a non-steroidal anti-inflammatory drug (NSAID) used to reduce pain, fever, and/or inflammation.',
    uses: ['Pain relief', 'Fever reduction', 'Anti-inflammatory', 'Migraine'],
    sideEffects: ['Nausea', 'Stomach upset', 'Heartburn'],
    dosages: '250-500mg every 4-6 hours as needed. Do not exceed 4000mg in 24 hours.',
    interactions:
      'Avoid use with other NSAIDs, blood thinners (e.g., Warfarin), and high doses of alcohol.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-002',
    name: 'Fauxcilin',
    genericName: 'Amoxicillinum fictum',
    description: 'Fauxcilin is a penicillin-type antibiotic used to treat a wide variety of bacterial infections.',
    uses: ['Bacterial infections', 'Strep throat', 'Pneumonia', 'Skin infections'],
    sideEffects: ['Diarrhea', 'Rash', 'Vomiting', 'Yeast infection'],
    dosages: '500mg every 8 hours or 875mg every 12 hours, for 7-10 days.',
    interactions:
      'May decrease the effectiveness of birth control pills. Inform your doctor about all medications you use.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-003',
    name: 'Simu-statin',
    genericName: 'Atorvastatinum simulata',
    description:
      'Simu-statin is used along with a proper diet to help lower "bad" cholesterol and fats (such as LDL, triglycerides) and raise "good" cholesterol (HDL) in the blood.',
    uses: ['High cholesterol', 'Heart disease prevention'],
    sideEffects: ['Muscle pain', 'Headache', 'Joint pain', 'Constipation'],
    dosages: '10-80mg once daily, with or without food.',
    interactions: 'Avoid grapefruit and grapefruit juice while taking this medication.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-004',
    name: 'Calpol',
    genericName: 'Paracetamol',
    description: 'A common analgesic and antipyretic used to treat mild to moderate pain and fever.',
    uses: ['Headache', 'Fever', 'Toothache', 'Cold & Flu'],
    sideEffects: ['Rarely, skin rashes', 'Allergic reactions'],
    dosages: '500mg-1000mg every 4-6 hours. Maximum 4000mg per day for adults.',
    interactions: 'Avoid with other paracetamol-containing products. Consult a doctor if you have liver problems.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-005',
    name: 'Brufen',
    genericName: 'Ibuprofen',
    description: 'A non-steroidal anti-inflammatory drug (NSAID) used for pain relief, fever reduction, and to reduce inflammation.',
    uses: ['Menstrual cramps', 'Arthritis', 'Sprains', 'Dental pain'],
    sideEffects: ['Stomach pain', 'Nausea', 'Increased risk of heart attack or stroke'],
    dosages: '200-400mg every 4-6 hours. Do not exceed 1200mg in 24 hours without medical advice.',
    interactions: 'Do not take with aspirin or other NSAIDs. Increased risk of stomach bleeding with alcohol.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-006',
    name: 'Cetriz',
    genericName: 'Cetirizine',
    description: 'An antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, itching eyes/nose, and sneezing.',
    uses: ['Hay fever', 'Allergic rhinitis', 'Urticaria (hives)'],
    sideEffects: ['Drowsiness', 'Dry mouth', 'Tiredness'],
    dosages: '10mg once daily.',
    interactions: 'Alcohol can increase drowsiness. Inform your doctor about other medications.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-007',
    name: 'Glycomet',
    genericName: 'Metformin',
    description: 'An oral diabetes medicine that helps control blood sugar levels, used for treating type 2 diabetes.',
    uses: ['Type 2 diabetes', 'Polycystic Ovary Syndrome (PCOS)'],
    sideEffects: ['Nausea', 'Diarrhea', 'Stomach upset', 'Metallic taste'],
    dosages: 'Starting dose is usually 500mg once or twice daily, increased as needed.',
    interactions: 'Avoid excessive alcohol. Certain contrast agents for X-rays can be problematic.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-008',
    name: 'Amlong',
    genericName: 'Amlodipine',
    description: 'A calcium channel blocker used to treat high blood pressure (hypertension) and chest pain (angina).',
    uses: ['Hypertension', 'Angina'],
    sideEffects: ['Swelling of ankles or feet', 'Dizziness', 'Headache', 'Flushing'],
    dosages: '5-10mg once daily.',
    interactions: 'Grapefruit juice can increase the effects of this medication. Check with your doctor about other heart medications.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-009',
    name: 'Asthalin',
    genericName: 'Salbutamol (Albuterol)',
    description: 'A bronchodilator that relaxes muscles in the airways and increases air flow to the lungs.',
    uses: ['Asthma', 'Chronic Obstructive Pulmonary Disease (COPD)'],
    sideEffects: ['Shakiness', 'Headache', 'Fast heartbeat', 'Nervousness'],
    dosages: '1-2 puffs from an inhaler every 4-6 hours as needed for bronchospasm.',
    interactions: 'Inform your doctor about any heart conditions or other medications, especially beta-blockers.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-010',
    name: 'Azee',
    genericName: 'Azithromycin',
    description: 'A macrolide antibiotic that fights bacteria. Used to treat many different types of infections caused by bacteria.',
    uses: ['Respiratory infections', 'Skin infections', 'Ear infections', 'Sexually transmitted diseases'],
    sideEffects: ['Diarrhea', 'Nausea', 'Abdominal pain', 'Vomiting'],
    dosages: 'Typically 500mg on day 1, followed by 250mg for 4 more days.',
    interactions: 'Antacids containing aluminum or magnesium can reduce its absorption.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-011',
    name: 'Zestril',
    genericName: 'Lisinopril',
    description: 'An ACE inhibitor used to treat high blood pressure and heart failure.',
    uses: ['Hypertension', 'Heart Failure', 'Post-Heart Attack'],
    sideEffects: ['Dry cough', 'Dizziness', 'Headache'],
    dosages: '10-40mg once daily.',
    interactions: 'Potassium supplements, salt substitutes, and other drugs that may increase potassium.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-012',
    name: 'Synthroid',
    genericName: 'Levothyroxine',
    description: 'A thyroid hormone replacement used to treat hypothyroidism.',
    uses: ['Hypothyroidism', 'Goiter'],
    sideEffects: ['Hair loss (temporary)', 'Increased sweating', 'Nervousness'],
    dosages: 'Varies based on patient needs, typically 25-300mcg once daily.',
    interactions: 'Calcium supplements, antacids, and iron can decrease absorption.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-013',
    name: 'Neurontin',
    genericName: 'Gabapentin',
    description: 'An anti-epileptic drug, also used to treat nerve pain.',
    uses: ['Seizures', 'Nerve pain from shingles', 'Restless legs syndrome'],
    sideEffects: ['Dizziness', 'Drowsiness', 'Loss of coordination'],
    dosages: '300-1200mg three times a day.',
    interactions: 'Antacids can reduce absorption. Avoid alcohol.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-014',
    name: 'Prilosec',
    genericName: 'Omeprazole',
    description: 'A proton pump inhibitor (PPI) that reduces stomach acid.',
    uses: ['GERD', 'Stomach ulcers', 'Heartburn'],
    sideEffects: ['Headache', 'Stomach pain', 'Diarrhea'],
    dosages: '20-40mg once daily before a meal.',
    interactions: 'May interact with clopidogrel, methotrexate, and certain other drugs.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-015',
    name: 'Zoloft',
    genericName: 'Sertraline',
    description: 'A selective serotonin reuptake inhibitor (SSRI) used to treat depression, anxiety, and other mood disorders.',
    uses: ['Depression', 'Panic disorder', 'OCD', 'PTSD'],
    sideEffects: ['Nausea', 'Insomnia', 'Dizziness', 'Sexual side effects'],
    dosages: '50-200mg once daily.',
    interactions: 'Do not take with MAOIs. Increased risk of bleeding with NSAIDs.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-016',
    name: 'Lasix',
    genericName: 'Furosemide',
    description: 'A loop diuretic ("water pill") that prevents your body from absorbing too much salt.',
    uses: ['Edema (fluid retention)', 'High blood pressure'],
    sideEffects: ['Increased urination', 'Dizziness', 'Dehydration', 'Electrolyte imbalance'],
    dosages: '20-80mg per day, can be split into two doses.',
    interactions: 'Can interact with many drugs, including digoxin and lithium. Monitor potassium levels.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-017',
    name: 'Xanax',
    genericName: 'Alprazolam',
    description: 'A benzodiazepine used to treat anxiety and panic disorders.',
    uses: ['Anxiety', 'Panic disorder'],
    sideEffects: ['Drowsiness', 'Dizziness', 'Memory problems', 'Dependence potential'],
    dosages: '0.25-0.5mg three times daily, adjusted as needed.',
    interactions: 'Avoid alcohol and other CNS depressants. Can be habit-forming.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-018',
    name: 'Celexa',
    genericName: 'Citalopram',
    description: 'An SSRI antidepressant used to treat depression.',
    uses: ['Major depressive disorder'],
    sideEffects: ['Nausea', 'Dry mouth', 'Sweating', 'Sleepiness'],
    dosages: '20-40mg once daily.',
    interactions: 'Risk of serotonin syndrome with other serotonergic drugs. Avoid MAOIs.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-019',
    name: 'Desyrel',
    genericName: 'Trazodone',
    description: 'An antidepressant that is also commonly used to treat insomnia.',
    uses: ['Depression', 'Insomnia'],
    sideEffects: ['Drowsiness', 'Dizziness', 'Dry mouth', 'Priapism (rare)'],
    dosages: '50-150mg at bedtime for insomnia; higher for depression.',
    interactions: 'Avoid alcohol. Risk of serotonin syndrome with other antidepressants.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-020',
    name: 'Cozaar',
    genericName: 'Losartan',
    description: 'An angiotensin II receptor blocker (ARB) used to treat high blood pressure.',
    uses: ['Hypertension', 'Kidney disease in diabetics'],
    sideEffects: ['Dizziness', 'Back pain', 'Cold-like symptoms'],
    dosages: '50-100mg once daily.',
    interactions: 'Can raise potassium levels, especially with potassium supplements.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-021',
    name: 'Deltasone',
    genericName: 'Prednisone',
    description: 'A corticosteroid that prevents the release of substances in the body that cause inflammation.',
    uses: ['Allergic disorders', 'Skin conditions', 'Arthritis', 'Asthma'],
    sideEffects: ['Increased appetite', 'Weight gain', 'Mood changes', 'Insomnia'],
    dosages: 'Varies widely depending on condition being treated. Taper off dose slowly.',
    interactions: 'Many drug interactions. Can increase blood sugar.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-022',
    name: 'Ultram',
    genericName: 'Tramadol',
    description: 'A narcotic-like pain reliever used to treat moderate to severe pain.',
    uses: ['Pain relief'],
    sideEffects: ['Dizziness', 'Constipation', 'Headache', 'Nausea', 'Risk of addiction'],
    dosages: '50-100mg every 4-6 hours as needed for pain.',
    interactions: 'Avoid alcohol and other CNS depressants. Risk of serotonin syndrome.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-023',
    name: 'Prozac',
    genericName: 'Fluoxetine',
    description: 'An SSRI antidepressant.',
    uses: ['Depression', 'OCD', 'Bulimia nervosa', 'Panic disorder'],
    sideEffects: ['Insomnia', 'Nausea', 'Headache', 'Sexual side effects'],
    dosages: '20-80mg per day.',
    interactions: 'Do not use with MAOIs or thioridazine.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-024',
    name: 'Coreg',
    genericName: 'Carvedilol',
    description: 'A beta-blocker used to treat heart failure and high blood pressure.',
    uses: ['Heart failure', 'Hypertension'],
    sideEffects: ['Dizziness', 'Tiredness', 'Shortness of breath', 'Weight gain'],
    dosages: 'Started at low dose (e.g., 3.125mg twice daily) and increased slowly.',
    interactions: 'Can mask signs of low blood sugar in diabetics. Many heart drug interactions.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-025',
    name: 'Coumadin',
    genericName: 'Warfarin',
    description: 'An anticoagulant (blood thinner) that reduces the formation of blood clots.',
    uses: ['Preventing blood clots', 'Atrial fibrillation', 'Pulmonary embolism'],
    sideEffects: ['Bleeding', 'Bruising easily', 'Nausea'],
    dosages: 'Dosage is highly individualized based on regular blood tests (INR).',
    interactions: 'Numerous food and drug interactions. Requires careful monitoring.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-026',
    name: 'Klonopin',
    genericName: 'Clonazepam',
    description: 'A benzodiazepine that is used to treat seizure disorders and panic disorder.',
    uses: ['Seizures', 'Panic disorder', 'Anxiety'],
    sideEffects: ['Drowsiness', 'Dizziness', 'Unsteadiness', 'Problems with coordination'],
    dosages: '0.5mg three times daily initially, can be increased to a max of 20mg/day.',
    interactions: 'Avoid alcohol and other CNS depressants. Can be habit-forming.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-027',
    name: 'Wellbutrin',
    genericName: 'Bupropion',
    description: 'An antidepressant medication used to treat major depressive disorder and seasonal affective disorder. Also used to help people stop smoking.',
    uses: ['Depression', 'Seasonal affective disorder', 'Smoking cessation'],
    sideEffects: ['Dry mouth', 'Nausea', 'Insomnia', 'Dizziness', 'Agitation'],
    dosages: '150mg once daily, may increase to 300mg/day.',
    interactions: 'Do not take with MAOIs. Increased risk of seizures at higher doses.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-028',
    name: 'Ambien',
    genericName: 'Zolpidem',
    description: 'A sedative, also called a hypnotic. It affects chemicals in the brain that may be unbalanced in people with sleep problems (insomnia).',
    uses: ['Insomnia'],
    sideEffects: ['Daytime drowsiness', 'Dizziness', 'Weakness', '"Drugged" feeling', 'Complex sleep behaviors'],
    dosages: '5-10mg before bedtime. Not for long-term use.',
    interactions: 'Avoid alcohol. Do not take with other sedative medications.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-029',
    name: 'Plavix',
    genericName: 'Clopidogrel',
    description: 'An antiplatelet medicine that prevents platelets in your blood from sticking together to form an unwanted blood clot.',
    uses: ['Prevention of heart attack', 'Prevention of stroke', 'Acute coronary syndrome'],
    sideEffects: ['Bleeding', 'Easy bruising', 'Nosebleeds', 'Headache'],
    dosages: '75mg once daily.',
    interactions: 'Interacts with other blood thinners, NSAIDs, and some PPIs like omeprazole.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-030',
    name: 'Cymbalta',
    genericName: 'Duloxetine',
    description: 'A serotonin-norepinephrine reuptake inhibitor (SNRI) used for major depressive disorder, generalized anxiety disorder, and certain types of pain.',
    uses: ['Depression', 'Anxiety', 'Diabetic peripheral neuropathy', 'Fibromyalgia'],
    sideEffects: ['Nausea', 'Dry mouth', 'Constipation', 'Drowsiness', 'Increased sweating'],
    dosages: '40-60mg per day, can be taken as a single dose or divided.',
    interactions: 'Do not take with MAOIs. Increased risk of bleeding with NSAIDs and anticoagulants.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-031',
    name: 'Tylenol',
    genericName: 'Acetaminophen',
    description: 'A pain reliever and a fever reducer. The exact mechanism of action is not known.',
    uses: ['Pain', 'Fever', 'Headache', 'Muscle aches'],
    sideEffects: ['Rare, but liver damage can occur with overdose.', 'Skin rash'],
    dosages: '325-650mg every 4-6 hours. Max 3000-4000mg per day for adults.',
    interactions: 'Avoid alcohol. Be cautious with other medications containing acetaminophen.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-032',
    name: 'Benadryl',
    genericName: 'Diphenhydramine',
    description: 'An antihistamine used to relieve symptoms of allergy, hay fever, and the common cold. Also used to treat insomnia and motion sickness.',
    uses: ['Allergies', 'Hives', 'Insomnia', 'Motion sickness'],
    sideEffects: ['Drowsiness', 'Dizziness', 'Dry mouth/nose/throat', 'Constipation'],
    dosages: '25-50mg every 4-6 hours for allergies. 50mg for sleep.',
    interactions: 'Increases effects of alcohol and other CNS depressants.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-033',
    name: 'Lexapro',
    genericName: 'Escitalopram',
    description: 'A selective serotonin reuptake inhibitor (SSRI) used to treat major depressive disorder and generalized anxiety disorder.',
    uses: ['Depression', 'Generalized Anxiety Disorder'],
    sideEffects: ['Nausea', 'Insomnia', 'Sexual dysfunction', 'Fatigue', 'Increased sweating'],
    dosages: '10mg once daily, may be increased to 20mg.',
    interactions: 'Do not take with MAOIs. Risk of serotonin syndrome.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-034',
    name: 'Lipitor',
    genericName: 'Atorvastatin',
    description: 'A statin medication used to prevent cardiovascular disease in those at high risk and treat abnormal lipid levels.',
    uses: ['High cholesterol', 'Prevention of cardiovascular events'],
    sideEffects: ['Joint pain', 'Diarrhea', 'Muscle pain (rarely rhabdomyolysis)'],
    dosages: '10-80mg once daily.',
    interactions: 'Avoid grapefruit juice. Many drug interactions.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-035',
    name: 'Norvasc',
    genericName: 'Amlodipine',
    description: 'A calcium channel blocker used to treat high blood pressure and chest pain (angina).',
    uses: ['Hypertension', 'Angina'],
    sideEffects: ['Swelling (edema)', 'Headache', 'Dizziness', 'Fatigue'],
    dosages: '5-10mg once daily.',
    interactions: 'Can interact with other blood pressure medications.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
    {
    id: 'med-036',
    name: 'Tenormin',
    genericName: 'Atenolol',
    description: 'A beta-blocker that affects the heart and circulation. Used to treat angina and hypertension.',
    uses: ['Hypertension', 'Angina', 'Post-heart attack'],
    sideEffects: ['Tiredness', 'Dizziness', 'Cold hands and feet', 'Depression'],
    dosages: '25-100mg once daily.',
    interactions: 'Can interact with other blood pressure drugs, NSAIDs, and diabetes medication.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-037',
    name: 'Flexeril',
    genericName: 'Cyclobenzaprine',
    description: 'A muscle relaxant used to relieve skeletal muscle spasms and associated pain.',
    uses: ['Muscle spasms', 'Pain from muscle injury'],
    sideEffects: ['Drowsiness', 'Dry mouth', 'Dizziness', 'Fatigue'],
    dosages: '5-10mg up to three times a day.',
    interactions: 'Do not use with MAOIs. Avoid alcohol and other CNS depressants.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-038',
    name: 'Singulair',
    genericName: 'Montelukast',
    description: 'A leukotriene receptor antagonist used for the maintenance treatment of asthma and to relieve symptoms of seasonal allergies.',
    uses: ['Asthma', 'Allergic rhinitis', 'Exercise-induced bronchoconstriction'],
    sideEffects: ['Headache', 'Stomach pain', 'Mood changes (rare)'],
    dosages: '10mg tablet once daily in the evening.',
    interactions: 'Generally well-tolerated with few major interactions.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-039',
    name: 'Crestor',
    genericName: 'Rosuvastatin',
    description: 'A statin medication, used to lower cholesterol and prevent cardiovascular disease.',
    uses: ['High cholesterol', 'Hypertriglyceridemia'],
    sideEffects: ['Headache', 'Muscle aches', 'Nausea', 'Weakness'],
    dosages: '5-40mg once daily.',
    interactions: 'Can interact with blood thinners and other cholesterol medications.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-040',
    name: 'Flonase',
    genericName: 'Fluticasone Propionate',
    description: 'A corticosteroid nasal spray that provides relief from allergy symptoms.',
    uses: ['Allergic rhinitis', 'Nasal congestion', 'Sneezing', 'Itchy, watery eyes'],
    sideEffects: ['Nosebleed', 'Headache', 'Nasal irritation', 'Sore throat'],
    dosages: '1-2 sprays in each nostril once daily.',
    interactions: 'Interactions are rare with the nasal spray form.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-041',
    name: 'Augmentin',
    genericName: 'Amoxicillin/clavulanate potassium',
    description: 'A combination penicillin-type antibiotic used to treat a wide variety of bacterial infections.',
    uses: ['Sinusitis', 'Pneumonia', 'Ear infections', 'Bronchitis', 'Urinary tract infections'],
    sideEffects: ['Diarrhea', 'Nausea', 'Vomiting', 'Skin rash'],
    dosages: 'Varies by infection type, typically 500mg or 875mg every 12 hours.',
    interactions: 'May decrease the effectiveness of birth control pills.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-042',
    name: 'Valium',
    genericName: 'Diazepam',
    description: 'A benzodiazepine used to treat anxiety, muscle spasms, and seizures.',
    uses: ['Anxiety', 'Alcohol withdrawal', 'Muscle spasms', 'Seizures'],
    sideEffects: ['Drowsiness', 'Tiredness', 'Muscle weakness', 'Ataxia (loss of coordination)'],
    dosages: '2-10mg, 2 to 4 times daily depending on condition.',
    interactions: 'High risk of severe drowsiness with alcohol and other CNS depressants. Habit-forming.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-043',
    name: 'Advair Diskus',
    genericName: 'Fluticasone/salmeterol',
    description: 'A combination of a corticosteroid and a long-acting beta-agonist used to control and prevent symptoms of asthma and COPD.',
    uses: ['Asthma (maintenance)', 'COPD'],
    sideEffects: ['Headache', 'Throat irritation', 'Hoarseness', 'Thrush (oral fungal infection)'],
    dosages: '1 inhalation twice daily, approximately 12 hours apart.',
    interactions: 'Beta-blockers can reduce effectiveness. Certain antifungal/antiviral drugs can increase side effects.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-044',
    name: 'Vyvanse',
    genericName: 'Lisdexamfetamine',
    description: 'A central nervous system stimulant used to treat attention deficit hyperactivity disorder (ADHD) and binge eating disorder.',
    uses: ['ADHD', 'Binge eating disorder'],
    sideEffects: ['Decreased appetite', 'Dry mouth', 'Insomnia', 'Anxiety', 'Increased heart rate'],
    dosages: '30mg once daily in the morning, can be adjusted up to 70mg.',
    interactions: 'Do not use with MAOIs. Can interact with antidepressants and blood pressure medications. Potential for abuse.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-045',
    name: 'Januvia',
    genericName: 'Sitagliptin',
    description: 'An oral diabetes medicine that helps control blood sugar levels by regulating the levels of insulin your body produces after eating.',
    uses: ['Type 2 diabetes'],
    sideEffects: ['Stuffy or runny nose', 'Sore throat', 'Headache', 'Upper respiratory infection'],
    dosages: '100mg once daily.',
    interactions: 'Few major drug interactions, but always inform doctor of all medications.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-046',
    name: 'Diovan',
    genericName: 'Valsartan',
    description: 'An angiotensin II receptor blocker (ARB) that keeps blood vessels from narrowing, which lowers blood pressure and improves blood flow.',
    uses: ['High blood pressure', 'Heart failure'],
    sideEffects: ['Dizziness', 'Headache', 'Tiredness', 'High potassium levels'],
    dosages: '80-320mg once daily.',
    interactions: 'Do not use with aliskiren in diabetics. Can interact with lithium and NSAIDs.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-047',
    name: 'Spiriva',
    genericName: 'Tiotropium',
    description: 'A long-acting anticholinergic bronchodilator used in the management of chronic obstructive pulmonary disease (COPD).',
    uses: ['COPD', 'Asthma'],
    sideEffects: ['Dry mouth', 'Constipation', 'Upper respiratory tract infection'],
    dosages: '1 inhalation (18 mcg) once daily via HandiHaler device.',
    interactions: 'Use with caution with other anticholinergic drugs.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-048',
    name: 'Lyrica',
    genericName: 'Pregabalin',
    description: 'An anti-convulsant and anti-epileptic drug, used to treat nerve pain and fibromyalgia.',
    uses: ['Neuropathic pain', 'Fibromyalgia', 'Seizures', 'Generalized anxiety disorder'],
    sideEffects: ['Dizziness', 'Drowsiness', 'Swelling in hands and feet', 'Weight gain'],
    dosages: '75-300mg twice daily.',
    interactions: 'Increases sedative effects of alcohol and other CNS depressants.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-049',
    name: 'Abilify',
    genericName: 'Aripiprazole',
    description: 'An atypical antipsychotic used to treat schizophrenia, bipolar disorder, and as an add-on for depression.',
    uses: ['Schizophrenia', 'Bipolar disorder', 'Depression', 'Tourette syndrome'],
    sideEffects: ['Headache', 'Agitation', 'Insomnia', 'Nausea', 'Weight gain'],
    dosages: '10-15mg once daily, can be adjusted up to 30mg.',
    interactions: 'Many interactions, especially with drugs affecting liver enzymes (e.g., ketoconazole).',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-050',
    name: 'Celebrex',
    genericName: 'Celecoxib',
    description: 'A nonsteroidal anti-inflammatory drug (NSAID) that specifically blocks COX-2, used to treat arthritis pain and inflammation.',
    uses: ['Osteoarthritis', 'Rheumatoid arthritis', 'Ankylosing spondylitis', 'Acute pain'],
    sideEffects: ['Stomach pain', 'Diarrhea', 'Gas', 'Increased risk of heart attack/stroke'],
    dosages: '100-200mg once or twice daily.',
    interactions: 'Increased bleeding risk with warfarin. Can affect blood pressure control.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-051',
    name: 'Effexor XR',
    genericName: 'Venlafaxine',
    description: 'A serotonin-norepinephrine reuptake inhibitor (SNRI) used to treat depression, anxiety, and panic disorder.',
    uses: ['Major depressive disorder', 'Generalized anxiety disorder', 'Social anxiety disorder', 'Panic disorder'],
    sideEffects: ['Nausea', 'Headache', 'Insomnia', 'Drowsiness', 'Increased blood pressure'],
    dosages: '37.5-225mg once daily (extended release).',
    interactions: 'Do not use with MAOIs. Risk of serotonin syndrome.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-052',
    name: 'Ritalin',
    genericName: 'Methylphenidate',
    description: 'A central nervous system stimulant used to treat Attention Deficit Hyperactivity Disorder (ADHD) and narcolepsy.',
    uses: ['ADHD', 'Narcolepsy'],
    sideEffects: ['Nervousness', 'Trouble sleeping', 'Loss of appetite', 'Increased heart rate'],
    dosages: 'Varies by form (short or long-acting), typically 5-20mg 2-3 times a day for short-acting.',
    interactions: 'Do not use with MAOIs. Can interact with blood pressure medications.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-053',
    name: 'Allegra',
    genericName: 'Fexofenadine',
    description: 'An antihistamine used to relieve allergy symptoms.',
    uses: ['Seasonal allergic rhinitis', 'Chronic hives (urticaria)'],
    sideEffects: ['Headache', 'Nausea', 'Drowsiness'],
    dosages: '60mg twice daily or 180mg once daily for adults.',
    interactions: 'Avoid taking with fruit juices (apple, orange, grapefruit).',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-054',
    name: 'Fosamax',
    genericName: 'Alendronate',
    description: 'A bisphosphonate used to treat and prevent osteoporosis.',
    uses: ['Osteoporosis in postmenopausal women', 'Osteoporosis in men', 'Paget\'s disease'],
    sideEffects: ['Stomach pain', 'Heartburn', 'Nausea', 'Esophageal irritation'],
    dosages: '70mg once weekly or 10mg once daily. Must be taken with a full glass of water on an empty stomach.',
    interactions: 'Calcium and antacids can interfere with absorption.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-055',
    name: 'Imitrex',
    genericName: 'Sumatriptan',
    description: 'A triptan medication used to treat migraine headaches.',
    uses: ['Migraine attacks', 'Cluster headaches'],
    sideEffects: ['Tingling/numbness', 'Feeling hot or cold', 'Drowsiness', 'Chest tightness'],
    dosages: '25-100mg tablet at onset of migraine, may repeat after 2 hours if needed.',
    interactions: 'Do not use with MAOIs or other triptans. Risk of serotonin syndrome with SSRIs/SNRIs.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-056',
    name: 'Flovent HFA',
    genericName: 'Fluticasone Propionate (Inhaler)',
    description: 'An inhaled corticosteroid used for the maintenance treatment of asthma.',
    uses: ['Asthma (long-term control)'],
    sideEffects: ['Thrush (oral fungal infection)', 'Hoarseness', 'Throat irritation'],
    dosages: 'Varies by severity, e.g., 88-440mcg twice daily.',
    interactions: 'Certain antiviral/antifungal drugs can increase levels.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-057',
    name: 'Remeron',
    genericName: 'Mirtazapine',
    description: 'An antidepressant used to treat depression, and often helps with insomnia and poor appetite.',
    uses: ['Major depressive disorder'],
    sideEffects: ['Drowsiness', 'Increased appetite', 'Weight gain', 'Dry mouth'],
    dosages: '15-45mg once daily at bedtime.',
    interactions: 'Do not use with MAOIs. Increases sedative effect of alcohol and benzodiazepines.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-058',
    name: 'Lantus',
    genericName: 'Insulin glargine',
    description: 'A long-acting insulin used to treat type 1 and type 2 diabetes.',
    uses: ['Type 1 Diabetes', 'Type 2 Diabetes'],
    sideEffects: ['Hypoglycemia (low blood sugar)', 'Injection site reactions', 'Weight gain'],
    dosages: 'Highly individualized, administered once daily by subcutaneous injection.',
    interactions: 'Many drugs can affect blood sugar levels.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-059',
    name: 'Xarelto',
    genericName: 'Rivaroxaban',
    description: 'A Factor Xa inhibitor anticoagulant (blood thinner) used to treat and prevent blood clots.',
    uses: ['Atrial fibrillation', 'Deep vein thrombosis (DVT)', 'Pulmonary embolism (PE)'],
    sideEffects: ['Increased risk of bleeding', 'Bruising', 'Nosebleeds'],
    dosages: 'Varies by condition, e.g., 20mg once daily for atrial fibrillation.',
    interactions: 'Many interactions, including with other anticoagulants, NSAIDs, and some antifungals.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-060',
    name: 'Viagra',
    genericName: 'Sildenafil',
    description: 'A PDE5 inhibitor used to treat erectile dysfunction (ED). Also used for pulmonary arterial hypertension.',
    uses: ['Erectile dysfunction', 'Pulmonary arterial hypertension'],
    sideEffects: ['Headache', 'Flushing', 'Upset stomach', 'Vision changes'],
    dosages: '50mg taken about 1 hour before sexual activity. Can be adjusted from 25-100mg.',
    interactions: 'Do not take with nitrates (e.g., nitroglycerin) due to severe drop in blood pressure.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-061',
    name: 'Bactrim',
    genericName: 'Sulfamethoxazole/trimethoprim',
    description: 'A combination antibiotic used to treat a variety of bacterial infections.',
    uses: ['Urinary tract infections (UTIs)', 'Bronchitis', 'Traveler\'s diarrhea'],
    sideEffects: ['Nausea', 'Vomiting', 'Loss of appetite', 'Skin rash'],
    dosages: 'One double strength (DS) tablet every 12 hours.',
    interactions: 'Can increase effects of warfarin. Risk of high potassium with ACE inhibitors.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-062',
    name: 'Diflucan',
    genericName: 'Fluconazole',
    description: 'An antifungal medication used to treat a variety of fungal and yeast infections.',
    uses: ['Vaginal yeast infections', 'Thrush (oral/esophageal)', 'Meningitis'],
    sideEffects: ['Headache', 'Nausea', 'Stomach pain', 'Changes in liver function tests'],
    dosages: '150mg single dose for vaginal yeast infection. Other uses require different dosing.',
    interactions: 'Many drug interactions, as it can affect liver enzymes.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-063',
    name: 'OxyContin',
    genericName: 'Oxycodone',
    description: 'A powerful opioid pain medication used to treat moderate to severe pain.',
    uses: ['Chronic severe pain'],
    sideEffects: ['Constipation', 'Nausea', 'Drowsiness', 'Dizziness', 'High potential for addiction'],
    dosages: 'Extended-release tablets, dosed every 12 hours. Highly controlled.',
    interactions: 'Avoid alcohol and other CNS depressants due to risk of respiratory depression.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-064',
    name: 'Keflex',
    genericName: 'Cephalexin',
    description: 'A cephalosporin antibiotic used to treat a number of bacterial infections.',
    uses: ['Respiratory tract infections', 'Skin infections', 'Bone infections', 'Ear infections'],
    sideEffects: ['Diarrhea', 'Nausea', 'Stomach pain', 'Headache'],
    dosages: '250-500mg every 6 hours.',
    interactions: 'May affect kidney function when taken with certain other drugs like metformin.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-065',
    name: 'Cipro',
    genericName: 'Ciprofloxacin',
    description: 'A fluoroquinolone antibiotic used to treat a number of bacterial infections.',
    uses: ['Urinary tract infections', 'Pneumonia', 'Infectious diarrhea', 'Skin infections'],
    sideEffects: ['Nausea', 'Diarrhea', 'Tendon rupture (rare but serious)', 'Nerve damage'],
    dosages: '250-750mg every 12 hours.',
    interactions: 'Do not take with dairy products or calcium-fortified juices alone. Interacts with blood thinners.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-066',
    name: 'Pepcid',
    genericName: 'Famotidine',
    description: 'An H2 blocker that works by decreasing the amount of acid the stomach produces.',
    uses: ['Heartburn', 'GERD', 'Stomach ulcers'],
    sideEffects: ['Headache', 'Dizziness', 'Constipation', 'Diarrhea'],
    dosages: '10-20mg for heartburn; 20-40mg for ulcers/GERD.',
    interactions: 'Generally well-tolerated with few interactions.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-067',
    name: 'Ativan',
    genericName: 'Lorazepam',
    description: 'A benzodiazepine used to treat anxiety disorders.',
    uses: ['Anxiety', 'Insomnia due to anxiety', 'Seizures'],
    sideEffects: ['Drowsiness', 'Dizziness', 'Weakness', 'Unsteadiness'],
    dosages: '1-2mg, 2 to 3 times daily for anxiety.',
    interactions: 'Avoid alcohol. High potential for dependence and sedation with other CNS depressants.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-068',
    name: 'Mobic',
    genericName: 'Meloxicam',
    description: 'A nonsteroidal anti-inflammatory drug (NSAID) used to treat pain or inflammation caused by arthritis.',
    uses: ['Osteoarthritis', 'Rheumatoid arthritis'],
    sideEffects: ['Stomach upset', 'Nausea', 'Dizziness', 'Increased risk of heart attack/stroke'],
    dosages: '7.5-15mg once daily.',
    interactions: 'Increased bleeding risk with anticoagulants. Can increase blood pressure.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-069',
    name: 'Jardiance',
    genericName: 'Empagliflozin',
    description: 'An SGLT2 inhibitor used to lower blood sugar in adults with type 2 diabetes. Also used to reduce the risk of cardiovascular death.',
    uses: ['Type 2 diabetes', 'Reduce cardiovascular risk'],
    sideEffects: ['Urinary tract infections', 'Yeast infections', 'Increased urination'],
    dosages: '10-25mg once daily in the morning.',
    interactions: 'Can cause dehydration, especially when used with diuretics.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  },
  {
    id: 'med-070',
    name: 'Seroquel',
    genericName: 'Quetiapine',
    description: 'An atypical antipsychotic used to treat schizophrenia, bipolar disorder, and as an add-on treatment for major depressive disorder.',
    uses: ['Schizophrenia', 'Bipolar disorder (manic and depressive episodes)', 'Depression'],
    sideEffects: ['Drowsiness', 'Dizziness', 'Weight gain', 'Dry mouth', 'Increased cholesterol'],
    dosages: 'Varies widely by condition, e.g., 300-800mg/day for schizophrenia, usually in divided doses.',
    interactions: 'Many interactions. Avoid alcohol. Can increase sedative effects of other drugs.',
    dataSource: 'Mock Pharmaceutical Database v1.2',
  }
];

export const doctors: Doctor[] = [
  {
    id: 'doc-001',
    name: 'Dr. Evelyn Reed',
    specialty: 'Cardiology',
    location: 'New York, NY',
    qualifications: ['MD', 'FACC'],
    experienceYears: 15,
    insurances: ['Blue Cross', 'Aetna', 'Cigna'],
    reviews: { count: 128, rating: 4.8 },
    image: {
      url: 'https://picsum.photos/seed/doc1/400/400',
      hint: 'female doctor',
    },
    dataSource: 'Mock Medical Licensing Board',
  },
  {
    id: 'doc-002',
    name: 'Dr. Samuel Chen',
    specialty: 'Pediatrics',
    location: 'Los Angeles, CA',
    qualifications: ['MD', 'FAAP'],
    experienceYears: 12,
    insurances: ['Kaiser Permanente', 'UnitedHealthcare'],
    reviews: { count: 215, rating: 4.9 },
    image: {
      url: 'https://picsum.photos/seed/doc4/400/400',
      hint: 'male pediatrician',
    },
    dataSource: 'Mock Medical Licensing Board',
  },
  {
    id: 'doc-003',
    name: 'Dr. Anika Patel',
    specialty: 'Dermatology',
    location: 'Chicago, IL',
    qualifications: ['MD', 'FAAD'],
    experienceYears: 8,
    insurances: ['Blue Cross', 'Humana', 'Aetna'],
    reviews: { count: 98, rating: 4.7 },
    image: {
      url: 'https://picsum.photos/seed/doc3/400/400',
      hint: 'female surgeon',
    },
    dataSource: 'Mock Medical Licensing Board',
  },
  {
    id: 'doc-004',
    name: 'Dr. Ben Carter',
    specialty: 'Orthopedics',
    location: 'Houston, TX',
    qualifications: ['DO', 'FAAOS'],
    experienceYears: 20,
    insurances: ['Cigna', 'UnitedHealthcare', 'Medicare'],
    reviews: { count: 150, rating: 4.8 },
    image: {
      url: 'https://picsum.photos/seed/doc2/400/400',
      hint: 'male doctor',
    },
    dataSource: 'Mock Medical Licensing Board',
  },
];

export const hospitals: Hospital[] = [
  {
    id: 'hosp-001',
    name: 'Apollo Hospital',
    location: 'Chennai, India',
    contact: '1860 500 1066',
    services: ['Cardiology', 'Oncology', 'Neurology', 'Transplants'],
    reviews: { count: 1500, rating: 4.8 },
    image: {
      url: "/hospitals/apollo.jpg",
      hint: 'large hospital',
    },
    dataSource: 'Mock Public Health Dataset',
  },
  {
    id: 'hosp-002',
    name: 'Fortis Hospital',
    location: 'Bengaluru, India',
    contact: '080 6621 4444',
    services: ['Orthopedics', 'Urology', 'Gastroenterology', 'Emergency Care'],
    reviews: { count: 1350, rating: 4.6 },
    image: {
      url: '/hospitals/fortis.png',
      hint: 'modern hospital',
    },
    dataSource: 'Mock Public Health Dataset',
  },
  {
    id: 'hosp-003',
    name: 'Medanta - The Medicity',
    location: 'Gurugram, India',
    contact: '0124 414 1414',
    services: ['Robotic Surgery', 'Cancer Institute', 'Heart Institute', 'Neurosciences'],
    reviews: { count: 1800, rating: 4.9 },
    image: {
      url: '/hospitals/medanta.jpeg',
      hint: 'medical complex',
    },
    dataSource: 'Mock Public Health Dataset',
  },
  {
    id: 'hosp-004',
    name: 'Narayana Health City',
    location: 'Bengaluru, India',
    contact: '080 7122 2222',
    services: ['Cardiac Surgery', 'Pediatric Care', 'Organ Transplants', 'Nephrology'],
    reviews: { count: 1600, rating: 4.7 },
    image: {
      url: '/hospitals/narayana.jpeg',
      hint: 'hospital building',
    },
    dataSource: 'Mock Public Health Dataset',
  },
  {
    id: 'hosp-005',
    name: 'PK Das Institute of Medical Sciences',
    location: 'Palakkad, Kerala',
    contact: '0491 255 6000',
    services: ['General Medicine', 'Surgery', 'Pediatrics', 'ENT'],
    reviews: { count: 950, rating: 4.5 },
    image: {
      url: '/hospitals/pk das.jpeg',
      hint: 'hospital building',
    },
    dataSource: 'Mock Public Health Dataset',
  },
  {
    id: 'hosp-006',
    name: 'Azeezia Medical College Hospital',
    location: 'Kollam, Kerala',
    contact: '0474 272 2222',
    services: ['Cardiology', 'Dermatology', 'Psychiatry', 'Emergency'],
    reviews: { count: 800, rating: 4.3 },
    image: {
      url: '/hospitals/azeezia.jpeg',
      hint: 'hospital exterior',
    },
    dataSource: 'Mock Public Health Dataset',
  },
  {
    id: 'hosp-007',
    name: 'Aster Medcity',
    location: 'Kochi, Kerala',
    contact: '0484 669 9999',
    services: ['Multi-Organ Transplant', 'Oncology', 'Cardiac Sciences', 'Neurosciences'],
    reviews: { count: 2100, rating: 4.9 },
    image: {
      url: '/hospitals/aster.jpeg',
      hint: 'modern hospital complex',
    },
    dataSource: 'Mock Public Health Dataset',
  },
  {
    id: 'hosp-008',
    name: 'Amrita Hospital',
    location: 'Kochi, Kerala',
    contact: '0484 285 1234',
    services: ['Cancer Care', 'Heart Care', 'Digestive Health', 'Bone & Joint'],
    reviews: { count: 2500, rating: 4.8 },
    image: {
      url: '/hospitals/amrita.jpeg',
      hint: 'large medical campus',
    },
    dataSource: 'Mock Public Health Dataset',
  },
];


